from time import sleep

def repeat_to_len(string, length):
    return (string * ((length//len(string))+1))[:length]

name = input('Enter your name ').upper()
namespaced = " ".join(name) + " <3"

print("              " + repeat_to_len(name, 9) + "                         " + repeat_to_len(name, 9))
sleep(0.3)
print("          " + repeat_to_len(name, 18) + "               " + repeat_to_len(name, 18))
sleep(0.3)
print("       " + repeat_to_len(name, 24) + "         " + repeat_to_len(name, 24))
sleep(0.3)
print("    " + repeat_to_len(name, 29) + "     " + repeat_to_len(name, 29))
sleep(0.3)
print("   " + repeat_to_len(name, 31) + "   " + repeat_to_len(name, 31))
sleep(0.3)
print("  " + repeat_to_len(name, 33) + " " + repeat_to_len(name, 33))
sleep(0.3)
print(" " + repeat_to_len(name, 69))
sleep(0.3)
print(" " + repeat_to_len(name, 69))
sleep(0.3)
print(repeat_to_len(name, 19) + "       " + repeat_to_len(name, 19) + "       " + repeat_to_len(name, 19))
sleep(0.3)
print(repeat_to_len(name, 16) + "              " + repeat_to_len(name, 11) + "              " + repeat_to_len(name, 16))
sleep(0.3)
print(repeat_to_len(name, 15) + "                  " + repeat_to_len(name, 5) + "                  " + repeat_to_len(name, 15))
sleep(0.3)
print(repeat_to_len(name, 14) + "      H A P P Y      " + repeat_to_len(name, 1) + "      H A P P Y      " + repeat_to_len(name, 14))
sleep(0.3)
print(repeat_to_len(name, 14) + "                                           " + repeat_to_len(name, 14))
sleep(0.3)
print(repeat_to_len(name, 14) + "      V A L E N T I N E ' S   D A Y !      " + repeat_to_len(name, 14))
sleep(0.3)
print(repeat_to_len(name, 14) + "                                           " + repeat_to_len(name, 14))
sleep(0.3)
print(repeat_to_len(name, 14) + namespaced.center(43, " ") + repeat_to_len(name, 14))
sleep(0.3)
print(" " + repeat_to_len(name, 15) + "                                       "+ repeat_to_len(name, 15))
sleep(0.3)
print("  " + repeat_to_len(name, 16) + "                                    " + repeat_to_len(name, 16))
sleep(0.3)
print("  " + repeat_to_len(name, 18) + "                                " + repeat_to_len(name, 18))
sleep(0.3)
print("   " + repeat_to_len(name, 19) + "                           " + repeat_to_len(name, 19))
sleep(0.3)
print("    " + repeat_to_len(name, 21) +"                     " + repeat_to_len(name, 21))
sleep(0.3)
print("     " + repeat_to_len(name, 23) + "               " + repeat_to_len(name, 23))
sleep(0.3)
print("      " + repeat_to_len(name, 25) + "         " + repeat_to_len(name, 25))
sleep(0.3)
print("       " + repeat_to_len(name, 27) + "   " + repeat_to_len(name, 27))
sleep(0.3)
print("         " + repeat_to_len(name, 26) + " " + repeat_to_len(name, 26))
sleep(0.3)
print("           " + repeat_to_len(name, 49))
sleep(0.3)
print("             " + repeat_to_len(name, 45))
sleep(0.3)
print("                " + repeat_to_len(name, 39))
sleep(0.3)
print("                   " + repeat_to_len(name, 33))
sleep(0.3)
print("                      " + repeat_to_len(name, 27))
sleep(0.3)
print("                          " + repeat_to_len(name, 19))
sleep(0.3)
print("                              " + repeat_to_len(name, 11))
sleep(0.3)
print("                                 " + repeat_to_len(name, 5))
sleep(0.3)
print("                                  " + repeat_to_len(name, 3))
sleep(0.3)
print("                                   " + repeat_to_len(name, 1))

